DEFAULT_MQ_HOST = "localhost"
DEFAULT_MQ_PORT = 5672
DEFAULT_MQ_USERNAME = "guest"
DEFAULT_MQ_PASSWORD = "guest"
DEFAULT_PUB_EXCHANGE_NAME = "p2p-publish"
DEFAULT_SUB_EXCHANGE_NAME = "p2p-subscribe"

DEFAULT_HTTP_HOST = "localhost"
DEFAULT_HTTP_PORT = 4030
